language: node_js
node_js:
  - "7"
  - "6"
install:
  - npm install
cache:
  directories:
    - ./node_modules
script:
  - npm run build
  - npm run rebuild
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNosandbox
  - xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
