os: osx
language: node_js
node_js:
  - "8"
install:
  - npm install
cache:
  directories:
    - ./node_modules
script:
  - npm run build
  - export CHROME_BIN=chromium-browser
  - npm run test -- --single-run --no-progress --browser=ChromeNosandbox
  - npm run e2e -- --no-progress --config=protractor-ci.conf.js
